### ISSUE TITLE
Windows 7 not supported

### ISSUE THREAD

**Issue by Markyparky56** [azhirnov/FrameGraph#1]
This is sort of a non-issue with Windows 7 going End-of-life within a year.

Due to the use of `EnterSynchronizationBarrier` and friends the minimum supported Windows version is Windows 8, according to [Microsoft Dev Center](https://docs.microsoft.com/en-us/windows/desktop/api/synchapi/nf-synchapi-entersynchronizationbarrier). 

Attempting to run Tests.FrameGraph.exe on Windows 7 errors out at start up with an "Entry Point Not Found" popup, relating to `EnterSynchronizatonBarrier" not being found in KERNERL32.dll.

**Comment by azhirnov** [comment]
There are some alternative implementations for the barrier.
I added check for target sdk version to enable win8 version.

**Comment by clojur** [comment]
Cmake is OK, but a lot of errors were reported during compilation. 
such as 
[ error C2514: “std::shared_lock”:Class has no constructor (compile source files G:\FrameGraph\tests\framegraph\ImplTests\ImplTest_Scene1.cpp) ]
