### ISSUE TITLE
Memory leaks when rendering loops

### ISSUE THREAD

**Issue by clojur** [azhirnov/FrameGraph#10]

**Comment by azhirnov** [comment]
which version?
how to reproduce?

I see small memory increment, will check it.

**Comment by clojur** [comment]
In October 2019, there will be a memory leak after rendering. At the beginning, it is not obvious, but with the running time of the program getting longer, the memory growth is very rapid. I don't know if the later version has been fixed.

**Comment by azhirnov** [comment]
there is fix for mem leak
https://github.com/azhirnov/FrameGraph/blob/dev/framegraph/Vulkan/CommandBuffer/VCommandBuffer.cpp#L125

**Comment by clojur** [comment]
After adding _mainAllocator.Discard(), the memory leak is not as obvious as before, but the memory leak still exists

**Comment by azhirnov** [comment]
I have checked all usage of linear allocators and they has no mem leak.
At other places used stl containers and smart pointers they shouldn't leak.
I will check it with memory profiler.

**Comment by azhirnov** [comment]
There is no mem leak at exit.
Profiler doesn't show memory increment in render loop, but task manager show small increment.
Maybe it is vulkan resources that profiler can't track.
