### ISSUE TITLE
Compile error when compiling with visual studio 2019

### ISSUE THREAD

**Issue by clojur** [azhirnov/FrameGraph#11]
E0020 Undefined identifier:"VK_ERROR_UNKNOWN"	VulkanLoader	G:\FrameGraph\extensions\vulkan_loader\VulkanCheckError.cpp	60

**Comment by azhirnov** [comment]
Your vulkan headers doesn't match with vulkan heders that used for FG development. For FG version 2020.1 header version must be 1.2.132.
Maybe you set cmake variable `FG_USE_VULKAN_SDK` to ON or `FG_EXTERNALS_USE_STABLE_VERSIONS` to OFF.

Also you can comment unknown variables/functions and comment BEGIN_ENUM_CHECKS/END_ENUM_CHECKS macro implementation to fix compilation errors.

**Comment by clojur** [comment]
External.glslang-main project compile error:
4>CMake Error at G:/FrameGraph/Build/external/External.glslang-main-prefix/src/External.glslang-main-stamp/External.glslang-main-install-Debug.cmake:37 (message):
4>  Command failed: 1
4>
4>   'H:/tools/cmake314/bin/cmake.exe' '-Dmake=' '-Dconfig=Debug' '-P' 'G:/FrameGraph/Build/external/External.glslang-main-prefix/src/External.glslang-main-stamp/External.glslang-main-install-Debug-impl.cmake'
4>
4>  See also
4>
4>    G:/FrameGraph/Build/external/External.glslang-main-prefix/src/External.glslang-main-stamp/External.glslang-main-install-*.log

4>CMake Error at G:/FrameGraph/Build/external/External.glslang-main-prefix/src/External.glslang-main-stamp/External.glslang-main-install-Debug-impl.cmake:9 (message):
4>  Command failed (1):
4>
4>   'H:/tools/cmake314/bin/cmake.exe' '--build' '.' '--config' 'Debug' '--target' 'glslang' 'install'

**Comment by azhirnov** [comment]
I have same error on some glslang versions.
Try to comment `install( ... SPIRVTargets ...)` in glslang/SPIRV/CMakeLists.txt

Current `dev` branch successfully compiled in debug mode 
https://travis-ci.com/github/azhirnov/FrameGraph/jobs/331842520
