### ISSUE TITLE
Question about the task

### ISSUE THREAD

**Issue by happydpc** [azhirnov/FrameGraph#15]
What's the design about the task in render graph? I want to use them to implement some dependencies with the nodes. What's the difference with [tbb](https://github.com/oneapi-src/oneTBB)or [task flow](https://github.com/taskflow/taskflow) library?

**Comment by azhirnov** [comment]
The idea of this FG-library - implement easy to use vulkan wrapper for prototyping.
This is not a thread pool library. You should create threads and add syncs manualy or use any library like tbb, task flow etc. FG allow you to use vulkan api from any thread without synchronizations, but each command buffer must be used in single thread. In debug mode FG have data race checks that notify you if you miss some syncs.

Task dependencies in FG is optional, they can be used to rearrange tasks to slightly incease performance. Without dependencies tasks will be executed in same order as you add it to command buffer.
For each command buffer FG tacks resource state and adds pipeline barriers and layout transitions. FG internally adds GPU-CPU syncs before reusing command buffers, reading from memory, etc.
If you use dependencies between command buffers, FG adds syncs between them.

Additionaly you can see multithreading tests [here](https://github.com/azhirnov/FrameGraph/tree/dev/tests/framegraph/ImplTests)

**Comment by happydpc** [comment]
Oh, that's awesome.

I will try to do some experiments on them. I had done some experiments on [pumex](https://github.com/pumexx/pumex) before (use tbb). It has some bugs and not maintained now. Hope we can make this render graph library better.

**Comment by happydpc** [comment]
"but each command buffer must be used in single thread", means merge them in render thread ?

**Comment by azhirnov** [comment]
> means merge them in render thread ?

Vulkan api require syncs if command buffer or command pool for that command buffer used in different threads.
FG doesn't protect command buffer by mutex for performance reasons, so if you need to use one command buffer in different threads you must add syncs.
The valid usage is in single thread call fg->Begin(), add tasks to cmd buffer, call fg->Execute(). Somewhere add dependencies between command buffers that recorded in different threads.
