### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by clojur** [azhirnov/FrameGraph#3]
Cmake is OK, but a lot of errors were reported during compilation.
such as
[ error C2514: “std::shared_lock”:Class has no constructor (compile source files G:\FrameGraph\tests\framegraph\ImplTests\ImplTest_Scene1.cpp) ]

**Comment by azhirnov** [comment]
which compiler do you use?

**Comment by clojur** [comment]
> which compiler do you use?

Visual Studio 15 2017

**Comment by clojur** [comment]
Which compiler does the author use?

**Comment by azhirnov** [comment]
I can't reproduce this errors yet.
I develop on VS 2017 and VS 2019, sometimes check on Linux with GCC 8.3

**Comment by clojur** [comment]
I use dev branch. What about yours? Std:: unique_lock lock {mutex}; can't this grammar be compiled and passed, C++ 17 grammar?

**Comment by clojur** [comment]
After testing GCC8.X compilation is no problem, but VS2017 chose the option of C++ 17 or compiled it.

**Comment by clojur** [comment]
After testing GCC8.X compilation is not a problem, but VS2017 selected the option of C++ 17 can not compile.

**Comment by azhirnov** [comment]
>  I use dev branch. What about yours?

dev branch should be stable

> Std:: unique_lock lock {mutex};

this is c++17 style

I've tested on 2 VS compilers: v14.16 and v14.21

**Comment by clojur** [comment]
My Compiler is [Visual Studio 2017 (v141) ]..

**Comment by clojur** [comment]
My compiler version is MSVC14.13. It's not a compiler problem, because I had several dependency libraries that could not be downloaded properly during cmake in China. Later, I downloaded them manually, cmake OK. Compiling with VS2017, I always reported C++ 17 grammatical errors. My operating system is Windows 7.

**Comment by clojur** [comment]
[cmake] Performing Test STD_FILESYSTEM_SUPPORTED - Failed
[cmake] Performing Test STD_CACHELINESIZE_SUPPORTED - Failed
[cmake] Performing Test STD_BARRIER_SUPPORTED - Failed

Will the failure of CMake above cause project compilation to fail?

**Comment by azhirnov** [comment]
> Will the failure of CMake above cause project compilation to fail?

No, this C++17 features is not required for FrameGraph and tests, but may be needed for some samples.

**Comment by clojur** [comment]
Update vs2017 to compile and pass
