### ISSUE TITLE
render deadlock

### ISSUE THREAD

**Issue by clojur** [azhirnov/FrameGraph#4]
A deadlock problem occurs during the execution of [frameGraph - > Flush ()]. The location screenshot is as follows:
in file VCommandPool.cpp ,137 line EXLOCK( _cmdGuard ); The debugging stops here and can't continue to debug.

**Comment by clojur** [comment]
The problem has been solved.std:: atomic_flag does not initialize clear ()

**Comment by azhirnov** [comment]
sorry, I missed notification.
atomic_flag was removed some time ago
