### ISSUE TITLE
Compile Error  Hash.h

### ISSUE THREAD

**Issue by liuhongyi0101** [azhirnov/FrameGraph#7]
// from https://stackoverflow.com/questions/2111667/compile-time-string-hashing  

Error C2131: The result of the expression is not constant

Do you have a solution? I would like to try your project ！！！！

Visual Studio 15 2017

**Comment by azhirnov** [comment]
Update you Visual studio.
It's already compiled and tested on CI with VS 2017.

**Comment by liuhongyi0101** [comment]
nice !  it,s ok,  thank you very much
